<a href="https://colab.research.google.com/github/404himel/LSTM/blob/main/LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
passage = """It was a busy Monday morning, and I woke up feeling tired.
The alarm had gone off at 6 AM, but I hit the snooze button several times before finally getting out of bed. The sun was barely rising, and the cool morning air filled the room.
I headed to the kitchen to make a cup of coffee. As I stood by the window, sipping my coffee, I thought about the long day ahead. I had several meetings, a few reports to finish, and a couple of calls to make.

After a quick shower, I dressed in my usual office clothes and grabbed my bag.
On my way out, I remembered to check if I had my wallet and keys.
"Where are my keys?" I muttered to myself as I searched through the bag. After a few moments, I found them tucked in a small pocket.
Relieved, I locked the door and headed to the bus stop. The street was busy with people rushing to work, and cars were honking in the distance.

I arrived at the office just in time for the first meeting. My boss greeted me with a nod as I walked into the conference room.
The meeting dragged on for nearly two hours, and by the end of it, I was exhausted. There was a lot to catch up on, and deadlines were fast approaching.
My colleagues and I exchanged notes and planned out the week.
"Let’s get this done by Friday," said my boss, as he handed out the assignments.

During lunch, I decided to take a short walk to clear my mind.
The weather was nice, and the fresh air helped me feel more focused.
 I stopped by a small café to grab a sandwich. As I sat down, I checked my phone and saw a few messages from friends, reminding me about our dinner plans for the weekend.
 I replied quickly and got back to the office.

The afternoon was busy. I spent hours working on the reports, barely looking up from my desk. Time flew by, and before I knew it, it was already 6 PM.
I packed my things and headed home, feeling tired but satisfied with the work I had done. On the way home, I decided to pick up some groceries for the week. The store was crowded, but I quickly gathered what I needed—milk, bread, vegetables, and a few snacks.

When I got home, I put the groceries away and sat down on the couch.
I scrolled through my phone, checking social media and catching up on the day’s news.
The evening felt peaceful. After a simple dinner of pasta and salad, I decided to watch a movie.
I turned on my favorite streaming service and browsed through the options.
After some time, I picked a comedy and settled in for the night.

As the movie ended, I realized how tired I was.
It had been a long day, and my eyes were starting to close.
I turned off the TV and headed to bed. As I lay down, I thought about the next day and all the things I still had to do.
But for now, I was content to relax. The sound of the city outside was calming, and soon, I drifted off to sleep, ready to do it all over again the next day."""

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts([passage])

In [ ]:
tokenizer.word_index

{'i': 1,
 'the': 2,
 'and': 3,
 'to': 4,
 'a': 5,
 'my': 6,
 'was': 7,
 'on': 8,
 'as': 9,
 'it': 10,
 'had': 11,
 'of': 12,
 'for': 13,
 'up': 14,
 'by': 15,
 'in': 16,
 'but': 17,
 'out': 18,
 'headed': 19,
 'day': 20,
 'few': 21,
 'after': 22,
 'busy': 23,
 'tired': 24,
 'off': 25,
 'about': 26,
 'office': 27,
 'through': 28,
 'with': 29,
 'were': 30,
 'time': 31,
 'me': 32,
 'decided': 33,
 'down': 34,
 'home': 35,
 'morning': 36,
 'feeling': 37,
 'at': 38,
 '6': 39,
 'several': 40,
 'before': 41,
 'bed': 42,
 'barely': 43,
 'air': 44,
 'room': 45,
 'make': 46,
 'coffee': 47,
 'thought': 48,
 'long': 49,
 'reports': 50,
 'bag': 51,
 'way': 52,
 'keys': 53,
 'small': 54,
 'work': 55,
 'meeting': 56,
 'boss': 57,
 'hours': 58,
 'week': 59,
 'done': 60,
 'sat': 61,
 'phone': 62,
 'from': 63,
 'dinner': 64,
 'quickly': 65,
 'got': 66,
 'things': 67,
 'some': 68,
 'groceries': 69,
 'movie': 70,
 'turned': 71,
 'next': 72,
 'all': 73,
 'do': 74,
 'monday': 75,
 'woke': 76,
 'alarm': 77,


In [ ]:
len(tokenizer.word_index)

259

In [ ]:
input_sequences = []
for sentence in passage.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [ ]:
input_sequences

[[10, 7],
 [10, 7, 5],
 [10, 7, 5, 23],
 [10, 7, 5, 23, 75],
 [10, 7, 5, 23, 75, 36],
 [10, 7, 5, 23, 75, 36, 3],
 [10, 7, 5, 23, 75, 36, 3, 1],
 [10, 7, 5, 23, 75, 36, 3, 1, 76],
 [10, 7, 5, 23, 75, 36, 3, 1, 76, 14],
 [10, 7, 5, 23, 75, 36, 3, 1, 76, 14, 37],
 [10, 7, 5, 23, 75, 36, 3, 1, 76, 14, 37, 24],
 [2, 77],
 [2, 77, 11],
 [2, 77, 11, 78],
 [2, 77, 11, 78, 25],
 [2, 77, 11, 78, 25, 38],
 [2, 77, 11, 78, 25, 38, 39],
 [2, 77, 11, 78, 25, 38, 39, 79],
 [2, 77, 11, 78, 25, 38, 39, 79, 17],
 [2, 77, 11, 78, 25, 38, 39, 79, 17, 1],
 [2, 77, 11, 78, 25, 38, 39, 79, 17, 1, 80],
 [2, 77, 11, 78, 25, 38, 39, 79, 17, 1, 80, 2],
 [2, 77, 11, 78, 25, 38, 39, 79, 17, 1, 80, 2, 81],
 [2, 77, 11, 78, 25, 38, 39, 79, 17, 1, 80, 2, 81, 82],
 [2, 77, 11, 78, 25, 38, 39, 79, 17, 1, 80, 2, 81, 82, 40],
 [2, 77, 11, 78, 25, 38, 39, 79, 17, 1, 80, 2, 81, 82, 40, 83],
 [2, 77, 11, 78, 25, 38, 39, 79, 17, 1, 80, 2, 81, 82, 40, 83, 41],
 [2, 77, 11, 78, 25, 38, 39, 79, 17, 1, 80, 2, 81, 82, 40, 83, 41

In [ ]:
max_len = max([len(x) for x in input_sequences])
max_len

48

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')
padded_input_sequences

array([[  0,   0,   0, ...,   0,  10,   7],
       [  0,   0,   0, ...,  10,   7,   5],
       [  0,   0,   0, ...,   7,   5,  23],
       ...,
       [  0,   0,   0, ..., 258, 259,   2],
       [  0,   0,   0, ..., 259,   2,  72],
       [  0,   0,   0, ...,   2,  72,  20]], dtype=int32)

In [ ]:
x = padded_input_sequences[:,:-1]

In [ ]:
y= padded_input_sequences[:,-1]

In [ ]:
x.shape

(533, 47)

In [ ]:
y.shape

(533,)

In [ ]:
x

array([[  0,   0,   0, ...,   0,   0,  10],
       [  0,   0,   0, ...,   0,  10,   7],
       [  0,   0,   0, ...,  10,   7,   5],
       ...,
       [  0,   0,   0, ...,  73, 258, 259],
       [  0,   0,   0, ..., 258, 259,   2],
       [  0,   0,   0, ..., 259,   2,  72]], dtype=int32)

In [ ]:
y

array([  7,   5,  23,  75,  36,   3,   1,  76,  14,  37,  24,  77,  11,
        78,  25,  38,  39,  79,  17,   1,  80,   2,  81,  82,  40,  83,
        41,  84,  85,  18,  12,  42,   2,  86,   7,  43,  87,   3,   2,
        88,  36,  44,  89,   2,  45,  19,   4,   2,  90,   4,  46,   5,
        91,  12,  47,   9,   1,  92,  15,   2,  93,  94,   6,  47,   1,
        48,  26,   2,  49,  20,  95,   1,  11,  40,  96,   5,  21,  50,
         4,  97,   3,   5,  98,  12,  99,   4,  46,   5, 100, 101,   1,
       102,  16,   6, 103,  27, 104,   3, 105,   6,  51,   6,  52,  18,
         1, 106,   4, 107, 108,   1,  11,   6, 109,   3,  53, 111,   6,
        53,   1, 112,   4, 113,   9,   1, 114,  28,   2,  51,  22,   5,
        21, 115,   1, 116, 117, 118,  16,   5,  54, 119,   1, 121,   2,
       122,   3,  19,   4,   2, 123, 124,   2, 125,   7,  23,  29, 126,
       127,   4,  55,   3, 128,  30, 129,  16,   2, 130, 131,  38,   2,
        27, 132,  16,  31,  13,   2, 133,  56,   6,  57, 134,  3

In [ ]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=260)

In [ ]:
y.shape

(533, 260)

In [ ]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Input

# Define the model
model = Sequential()
model.add(Input(shape=(56,)))
model.add(Embedding(input_dim=260, output_dim=100))
model.add(LSTM(150, return_sequences=True))
model.add(LSTM(150))
model.add(Dense(260, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy',metrics=['accuracy'])
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)              │ (None, 56, 100)             │          28,300 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_14 (LSTM)                       │ (None, 56, 150)             │         150,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_15 (LSTM)                       │ (None, 150)                 │         180,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 260)                 │          39,260 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 398,760 (1.52 MB)

 Trainable params: 398,760 (1.52 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(x,y,epochs=30)

Epoch 1/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - accuracy: 0.0353 - loss: 5.4898
Epoch 2/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 0.0685 - loss: 4.9906
Epoch 3/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0908 - loss: 4.8698
Epoch 4/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0852 - loss: 4.8486
Epoch 5/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0720 - loss: 4.9017
Epoch 6/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0564 - loss: 4.9398
Epoch 7/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0781 - loss: 4.8367
Epoch 8/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0804 - loss: 4.8398
Epoch 9/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0702 - loss: 4.8978
Epoch 10/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0962 - loss: 4.8664
Epoch 11/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0768 - loss: 4.7884
Epoch 12/30
17/17 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0661 -

In [ ]:
import time
import numpy as np
text = "It was a busy Monday"

for i in range(10):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=48, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
It was a busy Monday kitchen
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
It was a busy Monday kitchen and
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
It was a busy Monday kitchen and headed
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
It was a busy Monday kitchen and headed to
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
It was a busy Monday kitchen and headed to the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
It was a busy Monday kitchen and headed to the cup
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
It was a busy Monday kitchen and headed to the cup of
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
It was a busy Monday kitchen and headed to the cup of down
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
It was a busy Monday kitchen and headed to the cup of down i
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
It was a busy Monday kitchen and headed to the cup of down i coffee


In [ ]:

import time
import numpy as np
text = "My colleagues "

for i in range(10):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=56, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
My colleagues  i
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
My colleagues  i dressed
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
My colleagues  i dressed to
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
My colleagues  i dressed to headed
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
My colleagues  i dressed to headed and
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
My colleagues  i dressed to headed and the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
My colleagues  i dressed to headed and the office
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
My colleagues  i dressed to headed and the office helped
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
My colleagues  i dressed to headed and the office helped me
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
My colleagues  i dressed to headed and the office helped me me
